---
title: "[C++] noexcept - 예외를 발생시키지 않는 함수"
excerpt: "noexception에 대해 알아보자"

categories:
  - Cpp
tags:
  - [Cpp, exception]

toc : true
toc_sticky: true

last_modified_at: 2021-07-31
---

`noexception`이란 해당 함수가 예외를 발생시키지 않는다고   
컴파일러에게 명시해주는 것이다.

```cpp
int func1() noexcept
{
  //  code
}

int func2() noexcept(true)
{
  //  code
}
```

함수의 프로토타입 옆에 `noexcept`키워드를 붙여주며   
파라미터를 통해 `bool`값을 적어줄 수 있다.   
* `true`이면 예외가 발생하지 않는다는 것이고   
`false` 예외가 발생한다는 것이다.

실제 함수의 내부에서 예외가 발생하지 않는다는 것은 아니다.

예외가 발생할 경우 제대로 처리되지 않아 프로그램이 종료될 수 있다.

```cpp
int func() noexcept
{
  throw 1;
}

int main()
{
  try
  {
    func();
  }
  catch (int x)
  {
    std::cout << "Error : " << x << std::endl;
  }

  return 0;
}


//  warning: throw will always call terminate()
```

`noexcept`는 단순히 예외를 발생시키지 않는다고 알리는 힌트같은 것이다.   
또한 컴파일러가 `noexcept`함수에대해 미리 알고 다양한 최적화를 진행할 수 있게 된다.

> 추가적으로 C++11 부터 소멸자는 기본적으로 `noexcept`함수라고 한다.   
소멸자에서 예외가 생기면 안되기 때문이다.